<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Kytos Napps Repository - Welcome</title>
    <link rel='stylesheet' href='/static/user_ui/style.css'>
    <script src='/static/user_ui/jquery-3.1.1.min.js'>
    </script>
    <script src='/static/user_ui/main.js'> </script>
  </head>
  <body>
    <table border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">

            <!-- START CENTERED WHITE CONTAINER -->
            <!--
            <span class="preheader">This is preheader text. Some clients will show this text as a preview.</span>
            -->
            {% block main %}
            {% endblock %}

            <!-- START FOOTER -->
            <div class="footer">
              <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <span class="apple-link">Kytos Project. Network Apps  Repository.</span>
                  </td>
                </tr>
                <tr>
                </tr>
              </table>
            </div>

            <!-- END FOOTER -->

<!-- END CENTERED WHITE CONTAINER --></div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

