checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['napps_server/*', 'utils/*']
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
    dependencies:
        override:
            - true
